<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Datasource\ConnectionManager;
use Cake\Event\Event;
use Cake\Utility\Hash;

/**
 * Adgroups Controller
 *
 * @property \App\Model\Table\AdgroupsTable $Adgroups
 * @property \App\Model\Table\DevicesTable $Devices
 * @property  \App\Controller\Component\UploadImageComponent $UploadImage
 *
 * @method \App\Model\Entity\Adgroup[] paginate($object = null, array $settings = [])
 */
class AdgroupsController extends AppController
{

    public function initialize()
    {
        parent::initialize();

        // Include the FlashComponent
        $this->loadComponent('Flash');
        $this->loadComponent('UploadImage');

        // Load Files model
        $this->loadModel('FileAttachments');
        $this->loadModel('Logs');
    }

    public function beforeRender(Event $event)
    {
        $this->loadModel('Users');
        $this->loadModel('Devices');
        parent::beforeRender($event); // TODO: Change the autogenerated stub
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $adgroups = $this->Adgroups->find()->where(['delete_flag !=' => DELETED])->order(['id' => 'DESC'])->toArray();
        $flag = false;
        if (!empty($adgroups)) {
            $device_id = array();
            foreach ($adgroups as $k => $adgroup) {
                $device_id[] = $adgroup->device_id;
            }
            $show = array();
            foreach ($device_id as $k => $vl) {
                $show[] = json_decode($vl);
            }
            $merged = call_user_func_array('array_merge', $show);
            $devices = $this->Devices->find('all') ->where(['id NOT IN' => $merged])->combine('id','name')->toArray();
            if (empty($devices)) {
                $flag = true;
            }
        }
        $this->set(compact('adgroups', 'flag'));
        $this->set('_serialize', ['adgroups']);
    }

    /**
     * View method
     *
     * @param string|null $id Adgroup id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $adgroup = $this->Adgroups->get($id, [
            'contain' => []
        ]);

        $this->set('adgroup', $adgroup);
        $this->set('_serialize', ['adgroup']);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $conn = ConnectionManager::get('default');
        $conn->begin();
        $this->getAllData();
        $groups = $this->Adgroups->find()->select(['id', 'device_id'])->where(['delete_flag !=' => DELETED])->hydrate(false)->combine('id', 'device_id')->toList();
        if (!empty($groups)) {
            $device_id = array();
            foreach ($groups as $k => $vl) {
                $device_id[] = json_decode($vl);
            }
            $merged = call_user_func_array('array_merge', $device_id);
            $devices = $this->Devices->find('all') ->where(['id NOT IN' => $merged])->combine('id','name')->toArray();
        } else {
            $devices = $this->Devices->find()->where(['Devices.delete_flag !=' => DELETED])->select(['Devices.id', 'Devices.name'])->order(['Devices.id'=> 'DESC'])->combine('id', 'name')->toArray();
        }
        $adgroup = $this->Adgroups->newEntity();
        if ($this->request->is('post')) {
            $listNameDevice = ($this->getNameDevice($this->request->getData()['device_id']));
            $devices = $this->Devices->find('all')
                ->where(['id IN' => $this->request->getData()['device_id']])
                ->select(['id'])
                ->hydrate(false)
                ->toList();
            // Common Usage:
            $result_id_devices = Hash::extract($devices, '{n}.id');
            $data_service = array();
            if (!empty($this->request->data['file']['name'])) {
                $file = array(
                    'file' => $this->request->data['file']
                );
                $fileOK = $this->UploadImage->uploadFiles('upload/files', $file);
                unset($this->request->data['file']);
                if(array_key_exists('urls', $fileOK)) {
                    $data_service['path'] = $fileOK['urls'][0];
                    $data_service['image_backgroup'] = $file['file']['name'];
                }
            }
            $data_service['tile_name'] = $this->request->getData()['tile_name'];
            $data_service['langdingpage_id'] = $this->request->getData()['langdingpage_id'];
            $data_service['apt_device_number'] = $this->request->getData()['apt_device_number'];
            $this->publishall($result_id_devices, $data_service);
            $data_group = array(
                'name' => $this->request->getData()['name'],
                'device_id' => json_encode(array_values($this->request->getData()['device_id'])),
                'device_name' => ($listNameDevice),
                'description' => $this->request->getData()['description'],
                'langdingpage_id' => $this->request->getData()['langdingpage_id'],
                'path' => isset($data_service['path']) ? $data_service['path'] : '',
                'image_backgroup' => isset($data_service['image_backgroup']) ? $data_service['image_backgroup']:'',
                'tile_name' => $this->request->getData()['tile_name'],
                'apt_device_number' => $this->request->getData()['apt_device_number'],
            );
            $adgroup = $this->Adgroups->patchEntity($adgroup, $data_group);
            $adgroup->delete_flag = UN_DELETED;
            if (empty($adgroup->errors())) {
                if ($this->Adgroups->save($adgroup)) {
                    $conn->commit();
                    $this->redirect(['action' => 'index']);
                } else {
                    $conn->rollback();
                    $this->redirect(['action' => 'add']);
                }
            } else {
                $conn->rollback();
                $this->redirect(['action' => 'add']);
            }
        }
        $apt_device_number = $this->radompassWord();
        $this->set(compact('adgroup', 'apt_device_number', 'devices'));
        $this->set('_serialize', ['adgroup']);
    }

    /**
     * getNameUser method
     *
     * @param array $arr
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function getNameDevice(&$arr = array())
    {
        if (!empty($arr)) {
            $arr = $this->Devices->find()
            ->where(['id' => $arr],['id' => 'integer[]'])
            ->combine('id','name')
            ->toArray();
        }
        return json_encode(($arr));
    }
    /**
     * Edit method
     *
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit()
    {

        $this->autoRender = false;
        $conn = ConnectionManager::get('default');
        $conn->begin();
        if ($this->request->getData()) {
            $adgroups = $this->Adgroups->get($this->request->getData('id'), [
                'contain' => []
            ]);
            $adgroups = $this->Adgroups->patchEntity($adgroups, $this->request->getData());
            if (empty($adgroups->errors())) {
                if ($this->Adgroups->save($adgroups)) {
                    $conn->commit();
                } else {
                    $conn->rollback();
                }
            } else {
                $conn->rollback();
            }
            return $this->redirect(['action' => 'index']);
        }
    }

    /**
     * Delete method
     *
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete()
    {
        $this->autoRender = false;
        $conn = ConnectionManager::get('default');
        $conn->begin();
        $this->request->allowMethod(['post', 'delete']);
        if ($this->request->getData()) {
            $adgroups = $this->Adgroups->get($this->request->getData('id'));
            $adgroups->delete_flag = true;
            if($this->Adgroups->save($adgroups)){
                $conn->commit();
                die(json_encode(true));
            } else {
                $conn->rollback();
                die(json_encode(false));
            }
        }
    }

    /**
     * load method
     *
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */

    public function load()
    {
        $this->autoRender = false;
        if ($this->request->getData()) {
            $query = $this->Adgroups->find('all', array(
                'recursive' => -1,
                'conditions' => array(
                    'id' => $this->request->getData('id'),
                    'delete_flag !=' => DELETED
                ))
            );
            $row = $query->first()->toArray();
            if ($row) {
                $dataExist = array(
                    'id' => $row['id'],
                    'name' => $row['name'],
                    'description' => $row['description']
                );
                die(json_encode($dataExist));
            }
        }
    }

    /**
     * isNameExist method
     *
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */

    public function isNameExist()
    {
        $this->autoRender = false;
        if ($this->request->getData()) {
            if ($this->request->getData('backup_name') != $this->request->getData('name')) {
                $query = $this->Adgroups->find('all', array(
                    'recursive' => -1,
                    'conditions' => array(
                        'name' => $this->request->getData('name'),
                        'delete_flag !=' => DELETED
                    )));


                $number = $query->count();
                if (!$number) {
                    die(json_encode(true));
                } else {
                    die(json_encode(false));
                }
            } else {
                die(json_encode(true));
            }
        }
    }

    /**
     * isNameExistAdd method
     *
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function isNameExistAdd()
    {
        $this->autoRender = false;
        if ($this->request->getData()) {
            $query = $this->Adgroups->find('all', array(
                    'recursive' => -1,
                    'conditions' => array(
                        'name' => $this->request->getData('name'),
                        'delete_flag !=' => DELETED
                    ))
            );
            $number = $query->count();
            if (!$number) {
                die(json_encode(true));
            } else {
                die(json_encode(false));
            }
        }
    }

    /**
     * @param null $id
     * @return \Cake\Http\Response|null
     */
    public function detailGroup($id =null)
    {
        $conn = ConnectionManager::get('default');
        $conn->begin();
        if (!$this->Adgroups->exists($id)) {
            return $this->redirect(['action' => 'index']);
        }
        $this->getAllData();
        $adgroup = $this->Adgroups->get($id);
        if ($this->request->getData()) {
            $listUserid = $this->getNameDevice($this->request->getData()['device_id']);
            $data_group = array(
                'device_name' => $listUserid,
                'device_id' => json_encode($this->request->getData()['device_id']),
                'name' => $this->request->getData()['name'],
                'tile_name' => $this->request->getData()['tile_name'],
                'description' => $this->request->getData()['description'],
                'langdingpage_id' => $this->request->getData()['langdingpage_id'],
                'apt_device_number' => $this->request->getData()['apt_device_number'],
            );
            $data_device = array();
            if (!empty($this->request->data['file']['name'])) {
                // upload the file to the server
                $file = array(
                    'file' => $this->request->data['file']
                );
                $fileOK = $this->UploadImage->uploadFiles('upload/files', $file);
                unset($this->request->data['file']);

                if(array_key_exists('urls', $fileOK)) {
                    $data_device['path'] = $fileOK['urls'][0];
                    $data_device['image_backgroup'] = $file['file']['name'];
                    $data_group['path'] = $fileOK['urls'][0];
                    $data_group['image_backgroup'] = $file['file']['name'];
                }
            }
            $devices = $this->Devices->find('all')
                ->where(['id IN' => $this->request->getData()['device_id']])
                ->select(['id'])
                ->hydrate(false)
                ->toList();
            // Common Usage:
            $data_device['langdingpage_id'] = $this->request->getData()['langdingpage_id'];
            $data_device['apt_device_number'] = $this->request->getData()['apt_device_number'];
            $data_device['tile_name'] = $this->request->getData()['tile_name'];
            $result_id_devices = Hash::extract($devices, '{n}.id');
            $this->publishall($result_id_devices, $data_device);
            //$this->publishall($result_id_devices, $this->request->getData()['langdingpage_id']);
            $adgroup = $this->Adgroups->patchEntity($adgroup, $data_group);
            if (empty($adgroup->errors())) {
                if ($this->Adgroups->save($adgroup)) {
                    $conn->commit();
                    $this->Flash->success(__('The user has been saved.'));
                    return $this->redirect(['action' => 'index']);
                } else {
                    $conn->rollback();
                    $this->Flash->error(__('The device could not be saved. Please, try again.'));
                    return $this->redirect(['action' => 'edit'.'/'.$id]);
                }
            } else {
                $conn->rollback();
                $this->Flash->error(__('The device could not be saved. Please, try again.'));
                return $this->redirect(['action' => 'edit'.'/'.$id]);
            }
        }
        $apt_device_number = $this->radompassWord();
        $this->set(compact('adgroup','apt_device_number'));
    }

    public function publishall($list_id, $lan)
    {
        $conn = ConnectionManager::get('default');
        $conn->begin();
        $chk = true;
        $device = $this->Devices->find('all')->where(['id IN' => $list_id])->toArray();
        foreach ($device as $item) {
            $device = $this->Devices->patchEntity($item, $lan);
            if (empty($device->errors())) {
                if (!$this->Devices->save($device)) {
                    $chk = false;
                }
            }
        }
         if ($chk) {
             $conn->commit();
             return true;
         } else {
            $conn->rollback();
             return false;
         }
    }
}

