<?php

namespace App\Controller;

use App\Controller\AppController;
use App\Model\Entity\User;
use Cake\Datasource\ConnectionManager;
use Cake\Event\Event;
use Cake\Utility\Hash;

/**
 * Adgroups Controller
 *
 * @property \App\Model\Table\AdgroupsTable $Adgroups
 * @property \App\Model\Table\DevicesTable $Devices
 * @property \App\Model\Table\AdvsTable $Advs
 * @property \App\Model\Table\DeviceGroupsTable $DeviceGroups
 * @property \App\Model\Table\AdgroupChangeHistoriesTable $AdgroupChangeHistories
 * @property \App\Model\Table\AdgroupChangeHistory $AdgroupChangeHistory
 * @property  \App\Controller\Component\UploadImageComponent $UploadImage
 *
 * @method \App\Model\Entity\Adgroup[] paginate($object = null, array $settings = [])
 */
class AdgroupsController extends AppController
{

    public function initialize()
    {
        parent::initialize();

        // Include the FlashComponent
        $this->loadComponent('Flash');
        $this->loadComponent('UploadImage');

        // Load Files model
        $this->loadModel('Advs');
        $this->loadModel('Logs');
        $this->loadModel('DeviceGroups');
        $this->loadModel('FileAttachments');
        $this->loadModel('AdgroupChangeHistories');
    }

    public function beforeRender(Event $event)
    {
        $this->loadModel('Users');
        $this->loadModel('Devices');
        parent::beforeRender($event); // TODO: Change the autogenerated stub
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $users = $this->Auth->user();
        if ($users['role'] == User::ROLE_ONE) {
            $adgroups = $this->Adgroups->find('all', [
                'contain' => [
                    'Users' => function ($q) {
                        return $q
                            ->select([
                                'Users.id', 'Users.username'
                            ]);
                    }
                ],
                'conditions' => [
                    'Adgroups.delete_flag !=' => DELETED,
                ]
            ])->order(['Adgroups.id' => 'DESC']);
        } else {
            $adgroups = $this->Adgroups->find('all', [
                'contain' => [
                    'Users' => function ($q) {
                        return $q
                            ->select([
                                'Users.id', 'Users.username'
                            ]);
                    }
                ],
                'conditions' => [
                    'Adgroups.delete_flag !=' => DELETED,
                    'Adgroups.user_id_group' => $users['id']
                ]
            ])->order(['Adgroups.id' => 'DESC']);
        }
        $adgroups = $this->paginate($adgroups, ['limit' => 10, 'order' => [
            'Adgroups.created' => 'DESC']
        ])
            ->toArray();
        $flag = false;
        if (!empty($adgroups)) {
            $device_id = array();
            foreach ($adgroups as $k => $adgroup) {
                $device_id[] = $adgroup->device_id;
            }
            $show = array();
            foreach ($device_id as $k => $vl) {
                $show[] = json_decode($vl);
            }
            $merged = call_user_func_array('array_merge', $show);
            $devices = $this->Devices->find('all')->where(['id NOT IN' => $merged])->combine('id', 'name')->toArray();
            if (empty($devices)) {
                $flag = true;
            }
        }
        $this->getAllData();
        $this->set(compact('adgroups', 'flag'));
        $this->set('_serialize', ['adgroups']);
    }

    /**
     * View method
     *
     * @param string|null $id Adgroup id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $adgroup = $this->Adgroups->get($id, [
            'contain' => []
        ]);

        $this->set('adgroup', $adgroup);
        $this->set('_serialize', ['adgroup']);
    }

    /**
     * ** * *** ** * *** ** * *** ** * *** ** * *** ** * *** ** * *** ** * **
     * Add method group
     * @author hoannv
     *
     * @return void Redirects on successful add, renders view otherwise.
     *
     * * ** * *** ** * *** ** * *** ** * *** ** * *** ** * *** ** * *** ** * **
     */
    public function add()
    {
        $conn = ConnectionManager::get('default');
        $conn->begin();
        $this->getAllData();
        $user = $this->Auth->user();
        $groups = $this->Adgroups->find()
            ->select(['id', 'device_id'])
            ->where(['delete_flag !=' => DELETED])
            ->hydrate(false)
            ->combine('id', 'device_id')->toList();
        if (!empty($groups)) {
            $device_id = array();
            foreach ($groups as $k => $vl) {
                $device_id[] = json_decode($vl);
            }
            $merged = call_user_func_array('array_merge', $device_id);
            if ($user['role'] == User::ROLE_ONE) {
                $conditions = array(
                    'id NOT IN' => $merged,
                    'Devices.delete_flag !=' => DELETED,
                );
            } else {
                $conditions = array(
                    'id NOT IN' => $merged,
                    'delete_flag !=' => DELETED,
                    'user_id' => $user['id']
                );
            }
            $devices = $this->Devices->find('all')
                ->where($conditions)
                ->combine('id', 'name')->toArray();
        } else {
            if ($user['role'] == User::ROLE_ONE) {
                $conditions = array(
                    'Devices.delete_flag !=' => DELETED,
                );
            } else {
                $conditions = array(
                    'Devices.delete_flag !=' => DELETED,
                    'user_id' => $user['id']
                );
            }
            $devices = $this->Devices->find()
                ->where($conditions)
                ->select(['Devices.id', 'Devices.name'])
                ->order(['Devices.id' => 'DESC'])
                ->combine('id', 'name')->toArray();
        }
        $adgroup = $this->Adgroups->newEntity();
        if ($this->request->is('post')) {

            $image_adv = $this->request->getData('image_adv');
            $list_file = array();
            foreach ($image_adv as $k => $vl) {
                if ($vl['error'] != 4) {
                    $list_file[$k] = $vl;
                }
            }
            $list_link = $this->request->getData('link_adv');
            $data_file = array();
            if (!empty($list_file)) {
                // upload the file to the server
                $new_arr = array();
                //$list_file = $this->request->getData('image_adv');
                foreach ($list_file as $k => $vl) {
                    $new_arr[]['file'] = $vl;
                }
                $fileOK = array();
                foreach ($new_arr as $k => $vl) {
                    $fileOK[$k] = $this->UploadImage->uploadFiles('upload/files', $vl);
                }
                $result = Hash::extract($fileOK, '{n}.urls');
                $path = call_user_func_array('array_merge', $result);
                $image_up_load = Hash::extract($list_file, '{n}.name');
                foreach ($image_up_load as $k => $vl) {
                    $data_file[] = array(
                        'path' => $path[$k],
                        'name' => $vl,
                        'url_link' => isset($list_link[$k]) ? $list_link[$k] : '',
                        'active_flag' => 0
                    );
                }
                unset($this->request->data['image_adv']);
            } else {
                unset($this->request->data['image_adv']);
            }

            if ($this->request->data['tile_congratulations_return'] != '') {
                $packages = array_values($this->request->data['tile_congratulations_return']);
                $packages = (array_filter($packages));
                if (!empty($packages)) {
                    $this->request->data['tile_congratulations_return'] = json_encode($packages);
                } else {
                    $this->request->data['tile_congratulations_return'] = '';
                }
            }

            if ($this->request->data['packages'] != '') {
                $packages = array_values($this->request->data['packages']);
                $packages = (array_filter($packages));
                if (!empty($packages)) {
                    $this->request->data['packages'] = json_encode($packages);
                } else {
                    $this->request->data['packages'] = '';
                }
            }
            // todo option_tow setting
            if ($this->request->data['option_tow'] != '') {
                $option_tow = array_values($this->request->data['option_tow']);
                $option_tow = (array_filter($option_tow));
                if (!empty($option_tow)) {
                    $this->request->data['option_tow'] = json_encode($option_tow);
                } else {
                    $this->request->data['option_tow'] = '';
                }
            }
            $listNameDevice = ($this->getNameDevice($this->request->getData()['device_id']));
            $devices = $this->Devices->find()
                ->where(['id IN' => $this->request->getData()['device_id']])->select(['id'])
                ->hydrate(false)->toList();
            // Common Usage:
            $result_id_devices = Hash::extract($devices, '{n}.id');
            $data_service = array();

            if (!empty($this->request->data['logo_image']['error'] != 4)) {
                $list_file['file'] = $this->request->getData('logo_image');
                $fileOK = $this->UploadImage->uploadFiles('upload/files', $list_file);
                $path = $fileOK['urls'][0];
                $image_up_load = $list_file['file']['name'];
                if ($path != '') {
                    $this->request->data['path_logo'] = $path;
                }
                if ($image_up_load != '') {
                    $this->request->data['image_logo'] = $image_up_load;
                }
                unset($this->request->data['logo_image']);
            } else {
                unset($this->request->data['logo_image']);
            }
            if (!empty($this->request->data['file'][0]['error'] != 4)) {
                $new_arr = array();
                $list_file = $this->request->getData('file');
                foreach ($list_file as $k => $vl) {
                    $new_arr[]['file'] = $vl;

                }
                $fileOK = array();
                foreach ($new_arr as $k => $vl) {
                    $fileOK[$k] = $this->UploadImage->uploadFiles('upload/files', $vl);
                }
                $result = Hash::extract($fileOK, '{n}.urls');
                $path = call_user_func_array('array_merge', $result);
                $image_up_load = Hash::extract($list_file, '{n}.name');
                unset($this->request->data['file']);
            } else {
                $path = '';
                $image_up_load = '';
            }
            if ($path != '') {
                $data_service['path'] = implode(',', $path);
            }
            if ($image_up_load != '') {
                $data_service['image_backgroup'] = implode(',', $image_up_load);
            }
            $data_service['tile_name'] = $this->request->getData()['tile_name'];
            $data_service['landing_group_id'] = $this->request->getData()['langdingpage_id'];
            $data_service['apt_device_number'] = $this->request->getData()['apt_device_number'];
            //$this->publishall($result_id_devices, $data_service);
            $data_group_devices = array(
                'path' => isset($data_service['path']) ? $data_service['path'] : '',
                'address' => $this->request->getData()['address'],
                'packages' => isset($this->request->data['packages']) ? $this->request->data['packages'] : '',
                'type_adv' => isset($this->request->data['type_adv']) ? $this->request->data['type_adv'] : '',
                'tile_name' => $this->request->getData()['tile_name'],
                'path_logo' => isset($this->request->data['path_logo']) ? $this->request->data['path_logo'] : '',
                'device_id' => json_encode(array_values($this->request->getData()['device_id'])),
                'image_logo' => isset($this->request->data['title_connect']) ? $this->request->data['title_connect'] : '',
                'fb_fanpage' => isset($this->request->data['fb_fanpage']) ? $this->request->data['fb_fanpage'] : '',
                'option_tow' => isset($this->request->data['option_tow']) ? $this->request->data['option_tow'] : '',
                'fb_latitude' => isset($this->request->data['packages']) ? $this->request->data['fb_latitude'] : '',
                'device_name' => ($listNameDevice),
                'button_slow' => $this->request->getData('button_slow'),
                'button_fast' => $this->request->getData('button_fast'),
                'back_ground' => isset($data_service['image_backgroup']) ? $data_service['image_backgroup'] : '',
                'number_pass' => $this->request->getData()['apt_device_number'],
                'user_id_group' => isset($this->request->getData()['user_id_group']) ? $this->request->getData()['user_id_group'] : '',
                'fb_longtitude' => isset($this->request->data['packages']) ? $this->request->data['fb_longtitude'] : '',
                'hidden_connect' => isset($this->request->data['hidden_connect']) ? $this->request->data['hidden_connect'] : '',
                'title_connect' => isset($this->request->data['title_connect']) ? $this->request->data['title_connect'] : '',
                'fb_checkin_msg' => isset($this->request->data['fb_checkin_msg']) ? $this->request->data['fb_checkin_msg'] : '',
                'langdingpage_id' => $this->request->getData()['langdingpage_id'],
                'tile_congratulations_return' => isset($this->request->data['tile_congratulations_return']) ? $this->request->data['tile_congratulations_return'] : '',
            );

            $device_group = $this->DeviceGroups->newEntity();
            $device_group = $this->DeviceGroups->patchEntity($device_group, $data_group_devices);
            $data_group = array(
                'name' => $this->request->getData()['name'],
                'path' => isset($data_service['path']) ? $data_service['path'] : '',
                'address' => $this->request->getData()['address'],
                'type_adv' => isset($this->request->data['type_adv']) ? $this->request->data['type_adv'] : '',
                'packages' => isset($this->request->data['packages']) ? $this->request->data['packages'] : '',
                'device_id' => json_encode(array_values($this->request->getData()['device_id'])),
                'option_tow' => isset($this->request->data['option_tow']) ? $this->request->data['option_tow'] : '',
                'path_logo' => isset($this->request->data['path_logo']) ? $this->request->data['path_logo'] : '',
                'tile_name' => $this->request->getData()['tile_name'],
                'fb_fanpage' => isset($this->request->data['fb_fanpage']) ? $this->request->data['fb_fanpage'] : '',
                'image_logo' => isset($this->request->data['title_connect']) ? $this->request->data['title_connect'] : '',
                'fb_latitude' => isset($this->request->data['packages']) ? $this->request->data['fb_latitude'] : '',
                'device_name' => ($listNameDevice),
                'description' => $this->request->getData('description'),
                'button_slow' => $this->request->getData('button_slow'),
                'button_fast' => $this->request->getData('button_fast'),
                'fb_longtitude' => isset($this->request->data['packages']) ? $this->request->data['fb_longtitude'] : '',
                'user_id_group' => isset($this->request->getData()['user_id_group']) ? $this->request->getData()['user_id_group'] : '',
                'fb_checkin_msg' => isset($this->request->data['fb_checkin_msg']) ? $this->request->data['fb_checkin_msg'] : '',
                'hidden_connect' => isset($this->request->data['hidden_connect']) ? $this->request->data['hidden_connect'] : '',
                'title_connect' => isset($this->request->data['title_connect']) ? $this->request->data['title_connect'] : '',
                'image_backgroup' => isset($data_service['image_backgroup']) ? $data_service['image_backgroup'] : '',
                'langdingpage_id' => $this->request->getData()['langdingpage_id'],
                'apt_device_number' => $this->request->getData()['apt_device_number'],
                'tile_congratulations_return' => isset($this->request->data['tile_congratulations_return']) ? $this->request->data['tile_congratulations_return'] : '',
            );
            $adgroup = $this->Adgroups->patchEntity($adgroup, $data_group);
            $adgroup->delete_flag = UN_DELETED;
            if (empty($adgroup->errors())) {
                $save_ad = $this->Adgroups->save($adgroup);
                if ($save_ad) {
                    $group_id = $save_ad->id;
                    foreach ($data_file as $k => $item) {
                        $new_back_group = $this->Advs->newEntity();
                        $new_back_group = $this->Advs->patchEntity($new_back_group, $item);
                        $new_back_group->adgroup_id = $group_id;
                        if (!$this->Advs->save($new_back_group)) {
                            $conn->rollback();
                        }
                    }
                    //todo update data devices add to group
                    $device_adgroup = array(
                        'adgroup_id' => $group_id,
                    );
                    $this->publishall($result_id_devices, $device_adgroup);
                    $device_group->adgroup_id = $group_id;
                    if (empty($device_group->errors())) {
                        if ($this->DeviceGroups->save($device_group)) {
                            $conn->commit();
                            $this->redirect(['action' => 'index']);
                        } else {
                            $conn->rollback();
                            $this->redirect(['action' => 'add']);
                        }
                    }
                } else {
                    $conn->rollback();
                    $this->redirect(['action' => 'add']);
                }
            } else {
                $conn->rollback();
                $this->redirect(['action' => 'add']);
            }
        }
        $apt_device_number = $this->radompassWord();
        $this->set(compact('adgroup', 'apt_device_number', 'devices'));
        $this->set('_serialize', ['adgroup']);
    }

    /**
     * getNameUser method
     *
     * @param array $arr
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function getNameDevice(&$arr = array())
    {
        if (!empty($arr)) {
            $arr = $this->Devices->find()
                ->where(['id' => $arr], ['id' => 'integer[]'])
                ->combine('id', 'name')
                ->toArray();
        }
        return json_encode(($arr));
    }

    /**
     * Edit method
     *
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit()
    {

        $this->autoRender = false;
        $conn = ConnectionManager::get('default');
        $conn->begin();
        if ($this->request->getData()) {
            $adgroups = $this->Adgroups->get($this->request->getData('id'), [
                'contain' => []
            ]);
            $adgroups = $this->Adgroups->patchEntity($adgroups, $this->request->getData());
            if (empty($adgroups->errors())) {
                if ($this->Adgroups->save($adgroups)) {
                    $conn->commit();
                } else {
                    $conn->rollback();
                }
            } else {
                $conn->rollback();
            }
            return $this->redirect(['action' => 'index']);
        }
    }

    /**
     * Delete method
     *
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete()
    {
        $this->autoRender = false;
        $conn = ConnectionManager::get('default');
        $conn->begin();
        $this->request->allowMethod(['post', 'delete']);
        if ($this->request->getData()) {
            $adgroups = $this->Adgroups->get($this->request->getData('id'));
            $device_group = $this->DeviceGroups->find()
                ->where(['adgroup_id' => $this->request->getData('id'), 'device_id' => $adgroups->device_id, 'delete_flag !=' => DELETED])
                ->select('id')
                ->first()
                ->toArray();
            $this->removeAdgroupIdDevice(json_decode($adgroups->device_id));
            $result_change[] = array(
                'fields' => 'delete_flag',
                'from' => 'chưa xóa',
                'to' => 'đã xóa'
            );
            $change_log = array(
                'adgroup_id' => $adgroups->id,
                'contents' => json_encode($result_change, true)
            );
            $group = $this->DeviceGroups->get($device_group['id']);
            $group->delete_flag = true;
            $adgroups->delete_flag = true;
            $AdgroupChangeHistoriesTable = $this->AdgroupChangeHistories->newEntity();
            $AdgroupChangeHistoriesTable = $this->AdgroupChangeHistories->patchEntity($AdgroupChangeHistoriesTable, $change_log);
            $chk = true;
            if ($this->Adgroups->save($adgroups)) {
                if (!$this->AdgroupChangeHistories->save($AdgroupChangeHistoriesTable)) {
                    $chk = false;
                }
                if (!$this->DeviceGroups->save($group)) {
                    $chk = false;
                }

                if ($chk) {
                    $conn->commit();
                    die(json_encode(true));
                } else {
                    $conn->rollback();
                    die(json_encode(false));
                }

            } else {
                $conn->rollback();
                die(json_encode(false));
            }
        }
    }

    /**
     * load method
     *
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */

    public function load()
    {
        $this->autoRender = false;
        if ($this->request->getData()) {
            $query = $this->Adgroups->find('all', array(
                    'recursive' => -1,
                    'conditions' => array(
                        'id' => $this->request->getData('id'),
                        'delete_flag !=' => DELETED
                    ))
            );
            $row = $query->first()->toArray();
            if ($row) {
                $dataExist = array(
                    'id' => $row['id'],
                    'name' => $row['name'],
                    'description' => $row['description']
                );
                die(json_encode($dataExist));
            }
        }
    }

    /**
     * isNameExist method
     *
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */

    public function isNameExist()
    {
        $this->autoRender = false;
        if ($this->request->getData()) {
            if ($this->request->getData('backup_name') != $this->request->getData('name')) {
                $query = $this->Adgroups->find('all', array(
                    'recursive' => -1,
                    'conditions' => array(
                        'name' => $this->request->getData('name'),
                        'delete_flag !=' => DELETED
                    )));


                $number = $query->count();
                if (!$number) {
                    die(json_encode(true));
                } else {
                    die(json_encode(false));
                }
            } else {
                die(json_encode(true));
            }
        }
    }

    /**
     * isNameExistAdd method
     *
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function isNameExistAdd()
    {
        $this->autoRender = false;
        if ($this->request->getData()) {
            $query = $this->Adgroups->find('all', array(
                    'recursive' => -1,
                    'conditions' => array(
                        'name' => $this->request->getData('name'),
                        'delete_flag !=' => DELETED
                    ))
            );
            $number = $query->count();
            if (!$number) {
                die(json_encode(true));
            } else {
                die(json_encode(false));
            }
        }
    }

    /**
     *
     * ****************************************
     * update for group ...
     * @author hoannv
     *
     * @param null $id
     * @return \Cake\Http\Response|null
     *
     * * ****************************************
     */
    public function detailGroup($id = null)
    {
        $id = \UrlUtil::_decodeUrl($id);
        $conn = ConnectionManager::get('default');
        $conn->begin();
        if (!$this->Adgroups->exists(['id' => $id])) {
            return $this->redirect(['action' => 'index']);
        }
        $user = $this->Auth->user();
        $this->getAllData();
        $adgroup = $this->Adgroups->get($id);
        $groups = $this->Adgroups->find()
            ->select(['id', 'device_id'])
            ->where(['delete_flag !=' => DELETED])
            ->hydrate(false)
            ->combine('id', 'device_id')->toList();
        if (!empty($groups)) {
            $list_device_id = array();
            foreach ($groups as $group) {
                if ($adgroup->device_id != $group) {
                    $list_device_id[] = ($group);
                }
            }

            $device_id = array();
            foreach ($list_device_id as $k => $vl) {
                $device_id[] = json_decode($vl);
            }
            $device_list_id = json_decode($adgroup['device_id']);
            if (!empty($device_id)) {
                $merged = call_user_func_array('array_merge', $device_id);
                if ($user['role'] == User::ROLE_ONE) {
                    $conditions = array(
                        'id NOT IN' => $merged,
                        'delete_flag !=' => DELETED,
                    );
                } else {
                    $conditions = array(
                        'delete_flag !=' => DELETED,
                        'id IN' => $device_list_id
                    );
                }
                $devices = $this->Devices->find('all')
                    ->where($conditions)
                    ->combine('id', 'name')->toArray();
            } else {
                if ($user['role'] == User::ROLE_ONE) {
                    $conditions = array(
                        'Devices.delete_flag !=' => DELETED,
                    );
                } else {
                    $conditions = array(
                        'Devices.delete_flag !=' => DELETED,
                        'id IN' => $device_list_id
                    );
                }
                $devices = $this->Devices->find()
                    ->where($conditions)
                    ->select(['Devices.id', 'Devices.name'])
                    ->order(['Devices.id' => 'DESC'])
                    ->combine('id', 'name')
                    ->toArray();
            }
        } else {
            if ($user['role'] == User::ROLE_ONE) {
                $conditions = array(
                    'Devices.delete_flag !=' => DELETED,
                );
            } else {
                $conditions = array(
                    'Devices.delete_flag !=' => DELETED,
                    'user_id' => $user['id']
                );
            }
            $devices = $this->Devices->find()
                ->where($conditions)
                ->select(['Devices.id', 'Devices.name'])
                ->order(['Devices.id' => 'DESC'])
                ->combine('id', 'name')->toArray();
        }
        $device_group_id = $this->DeviceGroups->find()
            ->where(['adgroup_id' => $id, 'device_id' => $adgroup->device_id, 'delete_flag !=' => DELETED])
            ->select(['id'])->first()->toArray();
        $before_device = json_decode($adgroup->device_id);
        if ($this->request->is('post')) {
            $image_adv = $this->request->getData('image_adv');
            $list_file = array();
            foreach ($image_adv as $k => $vl) {
                if ($vl['error'] != 4) {
                    $list_file[$k] = $vl;
                }
            }
            $list_link = $this->request->getData('link_adv');
            if (!empty($list_file)) {
                // upload the file to the server
                $new_arr = array();
                //$list_file = $this->request->getData('image_adv');
                foreach ($list_file as $k => $vl) {
                    $new_arr[]['file'] = $vl;
                }
                $fileOK = array();
                foreach ($new_arr as $k => $vl) {
                    $fileOK[$k] = $this->UploadImage->uploadFiles('upload/files', $vl);
                }
                $result = Hash::extract($fileOK, '{n}.urls');
                $path = call_user_func_array('array_merge', $result);
                $image_up_load = Hash::extract($list_file, '{n}.name');
                $data_file = array();
                foreach ($image_up_load as $k => $vl) {
                    $data_file[] = array(
                        'adgroup_id' => $id,
                        'path' => $path[$k],
                        'name' => $vl,
                        'url_link' => isset($list_link[$k]) ? $list_link[$k] : '',
                        'active_flag' => 0
                    );
                }
                foreach ($data_file as $k => $item) {
                    $new_back_group = $this->Advs->newEntity();
                    $new_back_group = $this->Advs->patchEntity($new_back_group, $item);
                    if (!$this->Advs->save($new_back_group)) {
                        $conn->rollback();
                    }
                }
                unset($this->request->data['image_adv']);
            } else {
                unset($this->request->data['image_adv']);
            }

            if ($this->request->data['tile_congratulations_return'] != '') {
                $packages = array_values($this->request->data['tile_congratulations_return']);
                $packages = (array_filter($packages));
                if (!empty($packages)) {
                    $this->request->data['tile_congratulations_return'] = json_encode($packages);
                } else {
                    $this->request->data['tile_congratulations_return'] = '';
                }
            }
            // todo option_one thong tin khach hang
            if ($this->request->data['packages'] != '') {
                $packages = array_values($this->request->data['packages']);
                $packages = (array_filter($packages));
                if (!empty($packages)) {
                    $this->request->data['packages'] = json_encode($packages);
                } else {
                    $this->request->data['packages'] = '';
                }
            }
            // todo option_tow face sms
            if ($this->request->data['option_tow'] != '') {
                $option_tow = array_values($this->request->data['option_tow']);
                $option_tow = (array_filter($option_tow));
                if (!empty($packages)) {
                    $this->request->data['option_tow'] = json_encode($option_tow);
                } else {
                    $this->request->data['option_tow'] = '';
                }
            }
            $listUserid = $this->getNameDevice($this->request->getData()['device_id']);
            $data_group = array(
                'name' => $this->request->getData()['name'],
                'address' => $this->request->getData()['address'],
                'packages' => isset($this->request->data['packages']) ? $this->request->data['packages'] : '',
                'type_adv' => isset($this->request->data['type_adv']) ? $this->request->data['type_adv'] : '',
                'tile_name' => $this->request->getData()['tile_name'],
                'option_tow' => isset($this->request->data['option_tow']) ? $this->request->data['option_tow']:'',
                'device_id' => json_encode($this->request->getData()['device_id']),
                'fb_fanpage' => isset($this->request->data['fb_fanpage']) ? $this->request->data['fb_fanpage'] : '',
                'fb_latitude' => isset($this->request->data['packages']) ? $this->request->data['fb_latitude'] : '',
                'device_name' => $listUserid,
                'description' => $this->request->getData('description'),
                'button_slow' => $this->request->getData('button_slow'),
                'button_fast' => $this->request->getData('button_fast'),
                'fb_longtitude' => isset($this->request->data['packages']) ? $this->request->data['fb_longtitude'] : '',
                'title_connect' => isset($this->request->data['title_connect']) ? $this->request->data['title_connect'] : '',
                'fb_checkin_msg' => isset($this->request->data['fb_checkin_msg']) ? $this->request->data['fb_checkin_msg'] : '',
                'hidden_connect' => isset($this->request->data['hidden_connect']) ? $this->request->data['hidden_connect'] : '',
                'title_campaign' => isset($this->request->data['title_campaign']) ? $this->request->data['title_campaign'] : '',
                'langdingpage_id' => $this->request->getData()['langdingpage_id'],
                'apt_device_number' => $this->request->getData()['apt_device_number'],
                'tile_congratulations_return' => isset($this->request->data['tile_congratulations_return']) ? $this->request->data['tile_congratulations_return'] : '',
            );
            $image_logo = '';
            $path_logo = '';
            if (isset($this->request->data['logo_image'])) {
                if (!empty($this->request->data['logo_image']['error'] != 4)) {
                    $list_file['file'] = $this->request->getData('logo_image');
                    $fileOK = $this->UploadImage->uploadFiles('upload/files', $list_file);
                    $path = $fileOK['urls'][0];
                    $image_up_load = $list_file['file']['name'];
                    if ($path != '') {
                        $path_logo = $path;
                    }
                    if ($image_up_load != '') {
                        $image_logo = $image_up_load;
                    }
                    unset($this->request->data['logo_image']);
                } else {
                    unset($this->request->data['logo_image']);
                }
            }

            if (isset($path_logo) && $path_logo != '') {
                $data_group['path_logo'] = $path_logo;
                $data_group['image_logo'] = $image_logo;
            } else {
                $data_group['path_logo'] = $adgroup->path_logo;
                $data_group['image_logo'] = $adgroup->image_logo;
            }
            if (!empty($this->request->data['file'][0]['error'] != 4)) {
                $new_arr = array();
                $list_file = $this->request->getData('file');
                foreach ($list_file as $k => $vl) {
                    $new_arr[]['file'] = $vl;

                }
                $fileOK = array();
                foreach ($new_arr as $k => $vl) {
                    $fileOK[$k] = $this->UploadImage->uploadFiles('upload/files', $vl);
                }
                $result = Hash::extract($fileOK, '{n}.urls');
                $path = call_user_func_array('array_merge', $result);
                $image_up_load = Hash::extract($list_file, '{n}.name');
                if ($path != '') {
                    $data_group['path'] = implode(',', $path);
                }
                if ($image_up_load != '') {
                    $data_group['image_backgroup'] = implode(',', $image_up_load);
                }
                unset($this->request->data['file']);
            } else {
                unset($this->request->data['file']);
            }
            if (isset($data_group['path']) && $data_group['path'] != '') {
                $data_group['path'] = $data_group['path'] . ',' . $adgroup->path;
            } else {
                $data_group['path'] = $adgroup->path;
            }
            if (isset($data_group['image_backgroup']) && $data_group['image_backgroup'] != '') {
                $data_group['image_backgroup'] = $data_group['image_backgroup'] . ',' . $adgroup->image_backgroup;
            } else {
                $data_group['image_backgroup'] = $adgroup->image_backgroup;
            }
            // Common Usage:
            $device_group = array(
                'id' => $device_group_id['id'],
                'address' => $this->request->getData()['address'],
                'packages' => isset($this->request->data['packages']) ? $this->request->data['packages'] : '',
                'type_adv' => isset($this->request->data['type_adv']) ? $this->request->data['type_adv'] : '',
                'device_id' => json_encode($this->request->getData()['device_id']),
                'tile_name' => $this->request->getData()['tile_name'],
                'option_tow' => isset($this->request->data['option_tow']) ? $this->request->data['option_tow']:'',
                'adgroup_id' => $id,
                'fb_fanpage' => isset($this->request->data['fb_fanpage']) ? $this->request->data['fb_fanpage'] : '',
                'number_pass' => $this->request->getData()['apt_device_number'],
                'device_name' => $listUserid,
                'button_slow' => $this->request->getData('button_slow'),
                'button_fast' => $this->request->getData('button_fast'),
                'fb_latitude' => isset($this->request->data['packages']) ? $this->request->data['fb_latitude'] : '',
                'fb_longtitude' => isset($this->request->data['packages']) ? $this->request->data['fb_longtitude'] : '',
                'title_connect' => isset($this->request->data['title_connect']) ? $this->request->data['title_connect'] : '',
                'hidden_connect' => isset($this->request->data['hidden_connect']) ? $this->request->data['hidden_connect'] : '',
                'fb_checkin_msg' => isset($this->request->data['fb_checkin_msg']) ? $this->request->data['fb_checkin_msg'] : '',
                'title_campaign' => isset($this->request->data['title_campaign']) ? $this->request->data['title_campaign'] : '',
                'langdingpage_id' => $this->request->getData()['langdingpage_id'],
                'tile_congratulations_return' => isset($this->request->data['tile_congratulations_return']) ? $this->request->data['tile_congratulations_return'] : '',
            );
            if ($user['role'] == User::ROLE_ONE) {
                $data_group['user_id_group'] = isset($this->request->getData()['user_id_group']) ? $this->request->getData()['user_id_group'] : '';
                $device_group['user_id_group'] = isset($this->request->getData()['user_id_group']) ? $this->request->getData()['user_id_group'] : '';
            } else {
                $data_group['user_id_group'] = isset($adgroup->user_id_group) ? $adgroup->user_id_group : '';
                $device_group['user_id_group'] = isset($adgroup->user_id_group) ? $adgroup->user_id_group : '';
            }
            $device_group['path'] = $data_group['path'];
            $device_group['image_backgroup'] = $data_group['image_backgroup'];
            $device_group['path_logo'] = $data_group['path_logo'];
            $device_group['image_logo'] = $data_group['image_logo'];
            $list_remove_device_id = array();
            foreach ($before_device as $k => $vl) {
                if (!in_array($vl, $this->request->getData()['device_id'])) {
                    $list_remove_device_id[] = $vl;
                }
            }
            //todo update data devices add to group
            $result_id_devices = $this->request->getData()['device_id'];
            $device_adgroup = array(
                'adgroup_id' => $id,
                //'user_id' => $device_group['user_id_group']
            );
            $this->publishall($result_id_devices, $device_adgroup);
            $this->removeAdgroupIdDevice($list_remove_device_id);
            $log_before = $adgroup->toArray();
            unset($log_before['created']);
            unset($log_before['modified']);
            $group = $this->DeviceGroups->get($device_group_id['id']);
            $group = $this->DeviceGroups->patchEntity($group, $device_group);
            $adgroup = $this->Adgroups->patchEntity($adgroup, $data_group);
            $log_after = $adgroup->toArray();
            unset($log_after['created']);
            unset($log_after['modified']);
            $diffs = array_diff_assoc($log_before, $log_after);
            $result_change = array();
            if (!empty($diffs)) {
                foreach ($diffs as $k => $vl) {
                    $result_change[] = array(
                        'fields' => $k,
                        'from' => $vl,
                        'to' => $log_after[$k]
                    );
                }
            }
            $change_log = array(
                'adgroup_id' => $adgroup->id,
                'contents' => json_encode($result_change, true)
            );
            $AdgroupChangeHistoriesTable = $this->AdgroupChangeHistories->newEntity();
            $AdgroupChangeHistoriesTable = $this->AdgroupChangeHistories->patchEntity($AdgroupChangeHistoriesTable, $change_log);
            $chk = true;
            if (empty($adgroup->errors())) {
                if ($this->Adgroups->save($adgroup)) {
                    if (!$this->AdgroupChangeHistories->save($AdgroupChangeHistoriesTable)) {
                        $chk = false;
                    }
                    if (!$this->DeviceGroups->save($group)) {
                        $chk = false;
                    }
                    if ($chk) {
                        $conn->commit();
                        return $this->redirect(['action' => 'index']);
                    } else {
                        $conn->rollback();
                        return $this->redirect(['action' => 'detailGroup' . '/' . \UrlUtil::_encodeUrl($id)]);
                    }
                } else {
                    $conn->rollback();
                    return $this->redirect(['action' => 'detailGroup' . '/' . \UrlUtil::_encodeUrl($id)]);
                }
            } else {
                $conn->rollback();
                return $this->redirect(['action' => 'detailGroup' . '/' . \UrlUtil::_encodeUrl($id)]);
            }
        }
        $apt_device_number = $this->radompassWord();
        $adv = $this->Advs->find()->where(['adgroup_id' => $id, 'active_flag !=' => 1])->select(['id', 'adgroup_id', 'path', 'url_link'])->toArray();
        $this->set(compact('adgroup', 'apt_device_number', 'devices', 'list_users', 'adv'));
    }

    /**
     * Update langding group_id_ for devices
     *
     * @param $list_id
     * @param $lan
     * @return bool
     */
    public function publishall($list_id, $lan)
    {
        $conn = ConnectionManager::get('default');
        $conn->begin();
        $chk = true;
        $device = $this->Devices->find('all')->where(['id IN' => $list_id])->toArray();
        foreach ($device as $item) {
            $device = $this->Devices->patchEntity($item, $lan);
            if (empty($device->errors())) {
                if (!$this->Devices->save($device)) {
                    $chk = false;
                }
            }
        }
        if ($chk) {
            $conn->commit();
            return true;
        } else {
            $conn->rollback();
            return false;
        }
    }

    /**
     * @param $device_id
     * @return bool
     */
    public function removeAdgroupIdDevice($device_id)
    {
        $conn = ConnectionManager::get('default');
        $conn->begin();
        $chk = true;
        $adgroup = array(
            'adgroup_id' => ''
        );
        foreach ($device_id as $item) {
            $device = $this->Devices->get($item);
            $device = $this->Devices->patchEntity($device, $adgroup);
            if (empty($device->errors())) {
                if (!$this->Devices->save($device)) {
                    $chk = false;
                }
            }
        }
        if ($chk) {
            $conn->commit();
            return true;
        } else {
            $conn->rollback();
            return false;
        }
    }

    public function getUser()
    {
        $this->autoRender = false;
        if ($this->request->data) {
            $list_device_id = $this->request->getData('id');
            $role = $this->request->getData('role');
            if (!empty($list_device_id)) {
                $user_id = $this->Devices->find()
                    ->where(['id In' => $list_device_id, 'delete_flag !=' => DELETED])
                    ->select(['id', 'user_id'])
                    ->combine('id', 'user_id')
                    ->toArray();
//                if ($role == User::ROLE_ONE) {
//                    $conditions = array(
//                        'delete_flag !=' => DELETED,
//                        'id NOT IN' => 1,
//                        'id IN' => $user_id,
//                    );
//                } else {
//                    $conditions = array(
//                        'id IN' => $user_id,
//                        'delete_flag !=' => DELETED
//                    );
//                }
                $conditions = array(
                    'id IN' => $user_id,
                    'delete_flag !=' => DELETED
                );
                $username = $this->Users->find()
                    ->select(['id', 'username'])
                    ->where($conditions)
                    ->combine('id', 'username')
                    ->toArray();
                die(json_encode($username));
            } else {
                die(json_encode(array()));
            }
        }
    }

    public function deleteBackgroud()
    {
        $this->autoRender = false;
        if ($this->request->is('Post')) {
            $post_data = $this->request->getData();
            $ad = $this->Adgroups->find()->where(['id' => $post_data['ad_id'], 'delete_flag !=' => DELETED])->first();
            if (!empty($ad)) {
                $path = $ad['path'];
                $path = explode(',', $path);
                $image_bak = $ad['image_backgroup'];
                $image_bak = explode(',', $image_bak);
                unset($path[$post_data['id']]);
                unset($image_bak[$post_data['id']]);
                $list = array_values($path);
                $list_ad_path['path'] = implode(',', $list);
                $list_ad_path['image_backgroup'] = implode(',', $image_bak);
                $ad = $this->Adgroups->patchEntity($ad, $list_ad_path);
                if ($this->Adgroups->save($ad)) {
                    die(json_encode(true));
                } else {
                    die(json_encode(false));
                }
            } else {
                die(json_encode(false));
            }
        }
    }
}

