<?php
define('DELETE_FLAG', 'on');
define('REMEBER_ME', 'on');
define('ERROR_USERS_OR_PASSWORD', 'Sai tài khoản hoặc mật khẩu, hãy thử lại');
define('DELETED', true);
define('UN_DELETED', '0');
define('URL_LOAD', '/Landingpages/load');
define('URL_DELETE', '/Landingpages/delete');
define('URL_DEMO', '/Landingpages/lanedingDemo');
define('URL_LOAD_AD', '/Adgroups/load');
define('URL_LOAD_APT', '/Devices/load');
define('URL_DELETE_APT', '/Devices/delete');
define('URL_LOAD_CA', '/CampaignGroups/load');
define('URL_DELETE_CA', '/CampaignGroups/delete');
define('URL_DELETE_US', '/Users/delete');
define('URL_DELETE_CD', '/CampaignGroups/delete');
define('URL_DELETE_AD', '/Adgroups/delete');
define('URL_LOAD_SERVICE', '/ServiceGroups/load');
define('URL_DELETE_SERVICE', '/ServiceGroups/delete');
define('URL_DIRECTORY', APP . 'data/download' . DS);