<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Datasource\ConnectionManager;
use Cake\Event\Event;

/**
 * Adgroups Controller
 *
 * @property \App\Model\Table\AdgroupsTable $Adgroups
 *
 * @method \App\Model\Entity\Adgroup[] paginate($object = null, array $settings = [])
 */
class AdgroupsController extends AppController
{

    public function beforeRender(Event $event)
    {
        parent::beforeRender($event); // TODO: Change the autogenerated stub
    }
    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $query = $this->Adgroups
            ->find()
            ->select()
            ->where(['delete_flag !=' => DELETED])
            ->order(['id' => 'DESC']);
        $adgroups = $query->toArray();
        $this->set(compact('adgroups'));
        $this->set('_serialize', ['adgroups']);
    }

    /**
     * View method
     *
     * @param string|null $id Adgroup id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $adgroup = $this->Adgroups->get($id, [
            'contain' => []
        ]);

        $this->set('adgroup', $adgroup);
        $this->set('_serialize', ['adgroup']);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $conn = ConnectionManager::get('default');
        $conn->begin();
        $this->getAllData();
        $adgroup = $this->Adgroups->newEntity();
        if ($this->request->is('post')) {
            $listUserid = $this->getNameUser($this->request->getData()['user_id']);
            $data_group = array(
                'name' => $this->request->getData()['name'],
                'user_id' => $listUserid,
                'description' => $this->request->getData()['description'],
                'langdingpage_id' => $this->request->getData()['langdingpage_id'],
            );
            $adgroup = $this->Adgroups->patchEntity($adgroup, $data_group);
            $adgroup->delete_flag = UN_DELETED;
            if (empty($adgroup->errors())) {
                if ($this->Adgroups->save($adgroup)) {
                    $conn->commit();
                    $this->redirect(['action' => 'index']);
                } else {
                    $conn->rollback();
                    $this->redirect(['action' => 'add']);
                }
            } else {
                $conn->rollback();
                $this->redirect(['action' => 'add']);
            }
        }
        $this->set(compact('adgroup'));
        $this->set('_serialize', ['adgroup']);
    }

    /**
     * getNameUser method
     *
     * @param array $arr
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function getNameUser(&$arr = array())
    {
        if (!empty($arr)) {
            $arr = $this->Users->find()
            ->where(['id' => $arr],['id' => 'integer[]'])
            ->combine('id','username')
            ->toArray();
        }
        return json_encode($arr);
    }
    /**
     * Edit method
     *
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit()
    {

        $this->autoRender = false;
        $conn = ConnectionManager::get('default');
        $conn->begin();
        if ($this->request->getData()) {
            $adgroups = $this->Adgroups->get($this->request->getData('id'), [
                'contain' => []
            ]);
            $adgroups = $this->Adgroups->patchEntity($adgroups, $this->request->getData());
            if (empty($adgroups->errors())) {
                if ($this->Adgroups->save($adgroups)) {
                    $conn->commit();
                } else {
                    $conn->rollback();
                }
            } else {
                $conn->rollback();
            }
            return $this->redirect(['action' => 'index']);
        }
    }

    /**
     * Delete method
     *
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete()
    {
        $this->autoRender = false;
        $conn = ConnectionManager::get('default');
        $conn->begin();
        $this->request->allowMethod(['post', 'delete']);
        if ($this->request->getData()) {
            $adgroups = $this->Adgroups->get($this->request->getData('id'));
            $adgroups->delete_flag = true;
            if($this->Adgroups->save($adgroups)){
                $conn->commit();
                die(json_encode(true));
            } else {
                $conn->rollback();
                die(json_encode(false));
            }
        }
    }

    /**
     * load method
     *
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */

    public function load()
    {
        $this->autoRender = false;
        if ($this->request->getData()) {
            $query = $this->Adgroups->find('all', array(
                'recursive' => -1,
                'conditions' => array(
                    'id' => $this->request->getData('id'),
                    'delete_flag !=' => DELETED
                ))
            );
            $row = $query->first()->toArray();
            if ($row) {
                $dataExist = array(
                    'id' => $row['id'],
                    'name' => $row['name'],
                    'description' => $row['description']
                );
                die(json_encode($dataExist));
            }
        }
    }

    /**
     * isNameExist method
     *
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */

    public function isNameExist()
    {
        $this->autoRender = false;
        if ($this->request->getData()) {
            if ($this->request->getData('backup_name') != $this->request->getData('name')) {
                $query = $this->Adgroups->find('all', array(
                    'recursive' => -1,
                    'conditions' => array(
                        'name' => $this->request->getData('name'),
                        'delete_flag !=' => DELETED
                    )));


                $number = $query->count();
                if (!$number) {
                    die(json_encode(true));
                } else {
                    die(json_encode(false));
                }
            } else {
                die(json_encode(true));
            }
        }
    }

    /**
     * isNameExistAdd method
     *
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function isNameExistAdd()
    {
        $this->autoRender = false;
        if ($this->request->getData()) {
            $query = $this->Adgroups->find('all', array(
                    'recursive' => -1,
                    'conditions' => array(
                        'name' => $this->request->getData('name'),
                        'delete_flag !=' => DELETED
                    ))
            );
            $number = $query->count();
            if (!$number) {
                die(json_encode(true));
            } else {
                die(json_encode(false));
            }
        }
    }

    /**
     * @param null $id
     * @return \Cake\Http\Response|null
     */
    public function detailGroup($id =null)
    {
        $conn = ConnectionManager::get('default');
        $conn->begin();
        if (!$this->Adgroups->exists($id)) {
            return $this->redirect(['action' => 'index']);
        }
        $this->getAllData();
        $adgroup = $this->Adgroups->get($id);
        if ($this->request->getData()) {
            $listUserid = $this->getNameUser($this->request->getData()['user_id']);
            $data_group = array(
                'name' => $this->request->getData()['name'],
                'user_id' => $listUserid,
                'description' => $this->request->getData()['description'],
                'langdingpage_id' => $this->request->getData()['langdingpage_id'],
            );
            $adgroup = $this->Adgroups->patchEntity($adgroup, $data_group);
            if (empty($adgroup->errors())) {
                if ($this->Adgroups->save($adgroup)) {
                    $conn->commit();
                    $this->Flash->success(__('The user has been saved.'));
                    return $this->redirect(['action' => 'index']);
                } else {
                    $conn->rollback();
                    $this->Flash->error(__('The device could not be saved. Please, try again.'));
                    return $this->redirect(['action' => 'edit'.'/'.$id]);
                }
            } else {
                $conn->rollback();
                $this->Flash->error(__('The device could not be saved. Please, try again.'));
                return $this->redirect(['action' => 'edit'.'/'.$id]);
            }
        }
        $this->set(compact('adgroup'));
    }

}
